# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres:///ruby_stories_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgres:///ruby_stories_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>  # Render injects this
